# Site settings
title: Ruby Drops
email: abinoam@gmail.com
description: A fast introduction to Ruby
baseurl: /iboleto # the subpath of your site, e.g. /blog/
url: "http://abinoam.github.io" # the base hostname & protocol for your site
twitter_username: abinoamjr_en
github_username:  abinoam

# Build settings
markdown: kramdown
highlighter: rouge
